Implemented Screenshot Capture
avinashkranjan/logsuite pull request #9
Opened 2024-05-30 16:22 UTC by Saumya-28

#3 
## Implemented Screenshot Capture
![LogsuiteScreenshot](https://github.com/avinashkranjan/logsuite/assets/98171392/416485ac-555d-4a48-a3ee-9302ac7b4a23)

2024-05-31 07:15 UTC, avinashkranjan requested changes
When I've already mentioned in the Issue `Capture screenshots every 100ms and save them to device storage without taking permission` why you taking permission and handling it, create a solution where you can save the screenshots with permission of `EXTERNAL_STORAGE` from the user.

2024-05-31 18:35 UTC, Saumya-28 commented
@avinashkranjan I have updated the code , kindly check and let me know.

2024-05-31 18:40 UTC, avinashkranjan requested changes

2024-05-31 18:40 UTC, avinashkranjan commented on example/android/app/src/main/AndroidManifest.xml
I can still see Permissions for External Storage, Please remove them

2024-05-31 18:40 UTC, avinashkranjan commented on example/test/widget_test.dart
Please write test for your code..

2024-05-31 18:41 UTC, avinashkranjan commented
Hey @Saumya-28 , I have mentioned some changes, also, Write a small function for retriving the captured screenshots.

2024-06-01 07:39 UTC, avinashkranjan commented
No, A function where I can get all the SS, so, I can upload them to a server in the background.

2024-06-01 13:24 UTC, Saumya-28 commented
Hi @avinashkranjan !
I have updated the code, please check and let me know.

2024-06-05 10:55 UTC, Saumya-28 commented
Hi @avinashkranjan !
Kindly review the code and let me know.

2024-06-05 16:36 UTC, avinashkranjan commented
@Saumya-28, Caught up in something, will be reviewed by weekend.

2024-06-14 17:23 UTC, Saumya-28 commented
Hi @avinashkranjan could you please review the code.

2024-06-16 08:22 UTC, avinashkranjan approved these changes
LGTM..💯

2024-06-16 08:22 UTC, merged